name: Azure Pipelines Agent Image

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: azure-credentials

parameters:
  - name: imageType
    displayName: Image type
    type: string
    default: "UbuntuMinimal"
    values:
      - UbuntuMinimal
      - Ubuntu2004
      - Ubuntu2204
      - Windows2019
      - Windows2022
  - name: generateImage
    displayName: Generate Image
    type: boolean
    default: false
    values:
      - true
      - false
  - name: updateVMSS
    displayName: Update VMSS
    type: boolean
    default: true
    values:
      - true
      - false
  - name: debugPacker
    displayName: Debug Packer Image Creation
    type: boolean
    default: false
    values:
      - true
      - false

stages:
  - stage: Image
    displayName: Image Activities
    jobs:
      - job: Image
        timeoutInMinutes: 0

        steps:
          - task: AzureCLI@2
            displayName: Clone Repository
            enabled: ${{ parameters.generateImage }}
            inputs:
              azureSubscription: $(AzureServiceConnection)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                . $(Build.SourcesDirectory)/.scripts/Functions.ps1
                Copy-Repository -workingDirectory $(Build.SourcesDirectory)

          - task: AzureCLI@2
            displayName: Generate ${{ parameters.imageType }}
            enabled: ${{ parameters.generateImage }}
            inputs:
              azureSubscription: $(AzureServiceConnection)
              scriptType: pscore
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                . $(Build.SourcesDirectory)/.scripts/Functions.ps1
                Add-Image `
                  -workingDirectory $(Build.SourcesDirectory) `
                  -subscriptionId $(AzureSubscriptionId) `
                  -resourceGroupName $(ResourceGroupName) `
                  -imageType ${{ parameters.imageType }} `
                  -location $(Location) `
                  -debugPacker ${{ parameters.debugPacker }}
